# Generated by Django 4.1.2 on 2022-11-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentid', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=32)),
                ('status', models.CharField(max_length=32)),
            ],
        ),
    ]
