# Generated by Django 4.1.2 on 2022-11-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=255)),
                ('doctor', models.CharField(max_length=32, null=True)),
                ('location', models.CharField(max_length=20, null=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
