# Generated by Django 4.1.2 on 2022-11-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=32)),
                ('phone_number', models.CharField(max_length=32)),
                ('date', models.DateField()),
                ('comment', models.CharField(max_length=64)),
            ],
        ),
    ]
