# Generated by Django 4.1.2 on 2022-11-12 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='appointment',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='user.doctor', verbose_name='appointment'),
        ),
    ]
