# Generated by Django 4.1.2 on 2022-11-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_appointment_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
