# Generated by Django 4.1.2 on 2022-11-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_appointment_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('clinic_number', models.CharField(max_length=255)),
                ('clinic_picture', models.CharField(max_length=255)),
            ],
        ),
    ]
