# Generated by Django 4.1.2 on 2022-11-08 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_doctor_location'),
        ('user', '0004_location'),
    ]

    operations = [
    ]
