# Generated by Django 4.1.2 on 2022-11-11 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userinfo'),
        ('user', '0005_merge_0004_doctor_location_0004_location'),
    ]

    operations = [
    ]
