# Generated by Django 4.1.2 on 2022-11-11 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_merge_20221111_1307'),
        ('user', '0006_merge_20221111_1311'),
    ]

    operations = [
    ]
