# Generated by Django 4.1.2 on 2022-11-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_merge_20221111_1307'),
    ]

