# Generated by Django 4.1.2 on 2022-11-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_payment_doctor_remove_payment_paymentid_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='appointment',
            name='location',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='name',
            field=models.CharField(max_length=32, null=True),
        ),

    ]
